openapi: 3.0.0
info:
  title: ToDo-API
  description: A simple todo-api.
  version: 0.1.9
servers:
  - url: http://localhost:3000
paths:
  /todos:
    get:
      summary: Returns all todos
    responses:
      "200":
        description: "Successful get"
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
  